Models/Match.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FootBallWebLaba1.Models;

public partial class Match
{
    public int MatchId { get; set; }
    [Display(Name = "Дата матчу")]
    [DataType(DataType.Date)]
    [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
    public DateTime MatchDate { get; set; }
    [Display(Name = "Тривалість")]
    [Range(90,125, ErrorMessage = "Тривалість матча від 90 до 120 хвилин + 5 хвилин додаткового часу")]
    public short MatchDuration { get; set; }
    [Display(Name = "Стадіон")]
    public int StaidumId { get; set; }
    [Display(Name = "Команда хазяїв")]
    public int HostClubId { get; set; }
    [Display(Name = "Команда гостей")]
    public int GuestClubId { get; set; }
    [Display(Name = "Чемпіонат")]
    public int ChampionshipId { get; set; }

    public virtual Championship Championship { get; set; }
    [Display(Name = "Команда гостей")]
    public virtual Club GuestClub { get; set; }
    [Display(Name = "Команда хазяїв")]
    public virtual Club HostClub { get; set; }

    public virtual ICollection<ScoredGoal> ScoredGoals { get; } = new List<ScoredGoal>();
    [Display(Name = "Стадіон")]
    public virtual Stadium Stadium { get; set; }
}

Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FootBallWebLaba1.Models;
using System.Numerics;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.VariantTypes;

namespace FootBallWebLaba1.Controllers
{
    public class ClubsController : Controller
    {
        private readonly FootBallBdContext _context;

        public ClubsController(FootBallBdContext context)
        {
            _context = context;
        }

        // GET: Clubs
        public async Task<IActionResult> Index(string importSuccess)
        {
            ViewBag.importSuccess = importSuccess;
            return View(await _context.Clubs.ToListAsync());
        }

        // GET: Clubs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clubs == null)
            {
                return NotFound();
            }

            var club = await _context.Clubs
                .FirstOrDefaultAsync(m => m.ClubId == id);
            if (club == null)
            {
                return NotFound();
            }

            return View(club);
        }

        public async Task<IActionResult> PlayersList(int? id)
        {
            if (id == null || _context.Clubs == null)
            {
                return NotFound();
            }

            var club = await _context.Clubs
                .FirstOrDefaultAsync(m => m.ClubId == id);
            if (club == null)
            {
                return NotFound();
            }

            return RedirectToAction("IndexPlayers", "Players", new { id = club.ClubId, name = club.ClubId });
        }

        // GET: Clubs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clubs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClubId,ClubName,ClubOrigin,ClubPlayerQuantity,ClubCoachName,ClubEstablishmentDate")] Club club)
        {
            club.ClubPlayerQuantity = 0;
            if (ModelState.IsValid)
            {
                var clubName = _context.Clubs.FirstOrDefault(c => c.ClubName == club.ClubName);
                var clubCoach = _context.Clubs.FirstOrDefault(c => c.ClubCoachName == club.ClubCoachName);

                DateTime curDate = DateTime.Now;
                DateTime clubDate = club.ClubEstablishmentDate;

                if (clubDate > curDate)
                {
                    ModelState.AddModelError("ClubEstablishmentDate", "Дата створення клубу не відповідає дійсності");
                    return View(club);
                }

                if (clubCoach != null)
                {
                    ModelState.AddModelError("ClubCoachName", "Цей тренер уже тренує іншу команду");
                    return View(club);
                }

                if (clubName != null)
                {
                    ModelState.AddModelError("ClubName", "Команда з такою назвою уже існує");
                    return View(club);
                }

                _context.Add(club);
                await _context.SaveChangesAsync();
                return RedirectToAction("Create", "Stadiums", new { clubId = club.ClubId });
            }
            return View(club);
        }

        // GET: Clubs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clubs == null)
            {
                return NotFound();
            }

            var club = await _context.Clubs.FindAsync(id);
            if (club == null)
            {
                return NotFound();
            }
            return View(club);
        }

        // POST: Clubs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClubId,ClubName,ClubOrigin,ClubPlayerQuantity,ClubCoachName,ClubEstablishmentDate")] Club club)
        {
            if (id != club.ClubId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var clubName = _context.Clubs.FirstOrDefault(c => c.ClubName == club.ClubName && c.ClubId != club.ClubId);
                var clubCoach = _context.Clubs.FirstOrDefault(c => c.ClubCoachName == club.ClubCoachName && c.ClubId != club.ClubId);

                if (clubCoach != null)
                {
                    ModelState.AddModelError("ClubCoachName", "Цей тренер уже тренує іншу команду");
                    return View(club);
                }

                if (clubName != null)
                {
                    ModelState.AddModelError("ClubName", "Команда з такою назвою уже існує");
                    return View(club);
                }

                try
                {
                    _context.Update(club);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClubExists(club.ClubId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(club);
        }

        // GET: Clubs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clubs == null)
            {
                return NotFound();
            }

            var club = await _context.Clubs
                .FirstOrDefaultAsync(m => m.ClubId == id);
            if (club == null)
            {
                return NotFound();
            }

            return View(club);
        }

        // POST: Clubs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clubs == null)
            {
                return Problem("Entity set 'FootBallBdContext.Clubs'  is null.");
            }

            var club = await _context.Clubs
                .Include(c => c.Players)
                .Include(c => c.Stadiums)
                .FirstOrDefaultAsync(m => m.ClubId == id);

            var match = await _context.Matches
                .Where(m => m.HostClubId == id || m.GuestClubId == id)
                .Include(m => m.ScoredGoals)
                .FirstOrDefaultAsync();


            if (match != null)
            {
                foreach (var s in match.ScoredGoals)
                    _context.Remove(s);
                _context.Matches.Remove(match);
            }


            if (club != null)
            {
                foreach (var s in club.Stadiums)
                    _context.Remove(s);

                foreach (var p in club.Players)
                    _context.Remove(p);

                _context.Clubs.Remove(club);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool ClubExists(int id)
        {
            return _context.Clubs.Any(e => e.ClubId == id);
        }

        public ActionResult ExportToExcel()
        {
            using (XLWorkbook workbook = new XLWorkbook())
            {
                // Отримати дані з бази даних
                var clubs = _context.Clubs
                    .Include(c => c.Players)
                    .ThenInclude(p => p.Position)
                    .Include(c => c.Stadiums).ToList();

                // Створити новий Excel 
                var worksheet = workbook.Worksheets.Add("Matches");

                // Додати заголовки стовпців
                worksheet.Cell(1, 1).Value = "ClubId";
                worksheet.Cell(1, 2).Value = "ClubName";
                worksheet.Cell(1, 3).Value = "ClubOrigin";
                worksheet.Cell(1, 4).Value = "ClubCoachName";
                worksheet.Cell(1, 5).Value = "ClubEstablishmentDate";
                worksheet.Cell(1, 6).Value = "StadiumLocation";
                worksheet.Cell(1, 7).Value = "StadiumCapacity";
                worksheet.Cell(1, 8).Value = "StadiumEstablismentDate";
                worksheet.Cell(1, 9).Value = "PlayerName";
                worksheet.Cell(1, 10).Value = "PlayerNumber";
                worksheet.Cell(1, 11).Value = "PositionName";
                worksheet.Cell(1, 12).Value = "PlayerSalary";
                worksheet.Cell(1, 13).Value = "PlayerBirthDate";

                // Додати дані з бази даних
                for (int i = 0; i < clubs.Count; i++)
                {
                    var club = clubs[i];
                    worksheet.Cell(i + 2, 1).Value = club.ClubId;
                    worksheet.Cell(i + 2, 2).Value = club.ClubName;
                    worksheet.Cell(i + 2, 3).Value = club.ClubOrigin;
                    worksheet.Cell(i + 2, 4).Value = club.ClubCoachName;
                    worksheet.Cell(i + 2, 5).Value = club.ClubEstablishmentDate.ToShortDateString();
                    worksheet.Cell(i + 2, 6).Value = string.Join(",",club.Stadiums.Select(s => s.StadiumLocation));
                    worksheet.Cell(i + 2, 7).Value = string.Join(",", club.Stadiums.Select(s => s.StadiumCapacity));

Views/Matches/Create.cshtml
@model FootBallWebLaba1.Models.Match

@{
    ViewData["Title"] = "Create";
}

<h1>Додавання матчу до чемпіоната @ViewBag.ChampionshipName</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MatchDate" class="control-label"></label>
                <input asp-for="MatchDate" class="form-control" />
                <span asp-validation-for="MatchDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatchDuration" class="control-label"></label>
                <input asp-for="MatchDuration" class="form-control" />
                <span asp-validation-for="MatchDuration" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="StaidumId" class="control-label"></label>
                <select asp-for="StaidumId" class ="form-control" asp-items="ViewBag.StaidumId"></select>
            </div>*@
            <div class="form-group">
                <label asp-for="HostClubId" class="control-label"></label>
                <select asp-for="HostClubId" class ="form-control" asp-items="ViewBag.HostClubId"></select>
            </div>
            <div class="form-group">
                <label asp-for="GuestClubId" class="control-label"></label>
                <select asp-for="GuestClubId" class ="form-control" asp-items="ViewBag.GuestClubId"></select>
            </div>
       
            <input type="hidden" value="@ViewBag.ChampionshipId" name="ChampionshipId" />
 
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-success mt-1 mb-1" style="font-size:12px; padding:5px 7px; border-radius: 10px" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary mt-1 mb-1" style="font-size:12px; padding:5px 7px; border-radius: 10px">Назад до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Matches/Delete.cshtml
@model FootBallWebLaba1.Models.Match

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалення матчу</h1>

<h3>При видаленні матчу видалится вся інформація повязана з ним<div>Ви впевнені, що хочете продовжити?</div></h3>
<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MatchDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MatchDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MatchDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MatchDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Championship)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Championship.ChampionshipCountry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GuestClub)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GuestClub.ClubName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HostClub)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HostClub.ClubName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stadium)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stadium.StadiumLocation)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MatchId" />
        <input type="submit" value="Видалити" class="btn btn-danger mt-1 mb-1" style="font-size:12px; padding:5px 7px; border-radius: 10px" /> |
        <a asp-action="Index" class="btn btn-primary mt-1 mb-1" style="font-size:12px; padding:5px 7px; border-radius: 10px">Назад до списку</a>
    </form>
</div>

Views/Matches/Details.cshtml
@model FootBallWebLaba1.Models.Match

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Match</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MatchDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MatchDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MatchDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MatchDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Championship)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Championship.ChampionshipCountry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GuestClub)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GuestClub.ClubCoachName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HostClub)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HostClub.ClubCoachName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stadium)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stadium.StadiumLocation)
        </dd>
    </dl>
</div>
<div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.MatchId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Matches/Edit.cshtml
@model FootBallWebLaba1.Models.Match

@{
    ViewData["Title"] = "Edit";
}

<h1>Редагування матчу</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MatchId" />
            <div class="form-group">
                <label asp-for="MatchDate" class="control-label"></label>
                <input asp-for="MatchDate" class="form-control" />
                <span asp-validation-for="MatchDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatchDuration" class="control-label"></label>
                <input asp-for="MatchDuration" class="form-control" />
                <span asp-validation-for="MatchDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StaidumId" class="control-label"></label>
                <select asp-for="StaidumId" class="form-control" asp-items="ViewBag.StaidumId"></select>
                <span asp-validation-for="StaidumId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HostClubId" class="control-label"></label>
                <select asp-for="HostClubId" class="form-control" asp-items="ViewBag.HostClubId"></select>
                <span asp-validation-for="HostClubId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuestClubId" class="control-label"></label>
                <select asp-for="GuestClubId" class="form-control" asp-items="ViewBag.GuestClubId"></select>
                <span asp-validation-for="GuestClubId" class="text-danger"></span>
            </div>
            
            <input type="hidden" value="@ViewBag.ChampionshipId" name="ChampionshipId" />

            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-success mt-1 mb-1" style="font-size:12px; padding:5px 7px; border-radius: 10px" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary mt-1 mb-1" style="font-size:12px; padding:5px 7px; border-radius: 10px">Назад до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Matches/Index.cshtml
@model IEnumerable<FootBallWebLaba1.Models.Match>

@{
    ViewData["Title"] = "Матч за чемпіонатом";
}

<div>
    <h3>Оберіть файл для завантаження</h3>
    @using(Html.BeginForm("ImportMatchesFromExcel", "Matches", FormMethod.Post, new {enctype = "multipart/form-data", id = "frm-exel"}))
    {
        <div>
            Завантажити Exel-файл:
            <input type="file" name="fileExel" id="fileExel"/>
            <div>
                <input type="submit" value="Завантажити"/>
            </div>
        </div>
    }
</div>

<div>
    <h3>Завантажити інформацію про матчі</h3>
    <a asp-action="ExportMatchesToExcel" class="btn btn-primary mt-1 mb-1 d-inline-block" style="font-size:12px; padding:5px 7px; border-radius: 10px">Завантажити</a>
</div>

<h1>Матч чемпіонату @ViewBag.ChampionshipName</h1>


<p>
       @*@Html.ActionLink("Додати новий матч","Create", new {championshipId = ViewBag.ChampionshipId})*@
    <a href="@Url.Action("Create", new {championshipId = ViewBag.ChampionshipId})"> <input type="button" value="Додати новий матч" asp-action="Details" class="btn btn-success mt-1 mb-1" style="font-size:12px; padding:5px 7px; border-radius: 10px" /></a>
</p>
       

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MatchDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MatchDuration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Championship)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GuestClub)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HostClub)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stadium)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MatchDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatchDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Championship.ChampionshipName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GuestClub.ClubName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HostClub.ClubName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stadium.StadiumLocation)
            </td>
            <td>
                    <div class="d-inline-block">
                        <a asp-action="Details" class="btn btn-primary mt-1 mb-1 d-inline-block" style="font-size:12px; padding:5px 7px; border-radius: 10px" asp-route-id="@item.MatchId">Статистика матчу</a>
                        <a asp-controller="Stadiums" asp-action="DetailsStadium" class="btn btn-primary mt-1 mb-1 d-inline-block" style="font-size:12px; padding:5px 7px; border-radius: 10px" asp-route-id="@item.StaidumId">Стадіон</a>
                    </div>
                    <div class="d-inline-block">
                        <a asp-controller="Clubs" asp-action="Details" class="btn btn-primary mt-1 mb-1 d-inline-block" style="font-size:12px; padding:5px 7px; border-radius: 10px" asp-route-id="@item.HostClubId">Команда хазяїв</a>
                        <a asp-controller="Clubs" asp-action="Details" class="btn btn-primary mt-1 mb-1 d-inline-block" style="font-size:12px; padding:5px 7px; border-radius: 10px" asp-route-id="@item.GuestClubId">Команда гостей</a>
                    </div>
                    <a asp-action="Edit" class="btn btn-info mt-1 mb-1 d-inline-block" style="font-size:12px; padding:5px 7px; border-radius: 10px" asp-route-id="@item.MatchId">Редагувати</a> 
                    <a asp-action="Delete" class="btn btn-danger mt-1 mb-1 d-inline-block" style="font-size:12px; padding:5px 7px; border-radius: 10px" asp-route-id="@item.MatchId">Видалити</a>
                    
            </td>
        </tr>
}
    </tbody>
</table>